version: '3'

services:
  nginx:
    image: nginx:1.24.0
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server1
      - server2

  server1:
    image: node:20
    command: ["npm", "start"]
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      - SERVERNAME=server1
    volumes:
      - ./src:/app
    working_dir: /app
    ports:
      - "3000:3000"

  server2:
    image: node:20
    command: ["npm", "start"]
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      - SERVERNAME=server2
    volumes:
      - ./src:/app
    working_dir: /app
    ports:
      - "3001:3000"
  server3:
    image: node:20
    command: ["npm", "start"]
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      - SERVERNAME=BACKUP
    volumes:
      - ./src:/app
    working_dir: /app
    ports:
      - "3002:3000"
