version: '3'

services:
  nginx:
    image: nginx:1.24.0
    ports:
      - "3005:80"
    volumes:
      - ./src/photo.jpg:/var/www/html/photo.jpg
      - ./src/index.html:/var/www/html/index.html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server1

  server1:
    image: node:20
    command: ["npm", "start"]
    environment:
      - SERVERNAME=server1
    volumes:
      - ./src:/app
    working_dir: /app
    ports:
      - "3000:3000"
